site_name: Documentation Simula 2018
pages: 
     - Home: index.md 
     #- About: about.md

theme: readthedocs

mkdocs.yml
docs/
    CNAME
    index.md
    about.md
    license.md
    img/
        Screen Shot 2018-06-04 at 9.49.19 AM.png
 
